### ISSUE TITLE
Round details

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/grants-stack#30]

**Comment by jose-garrofe** [comment]
We should move this message to the In Review tab, since user can't approve/reject from the Received status anymore. We could also keep one on the Received tab but changing the status on the message to "Save in gas by changing multiple applications to In Review status at once."

![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/e5c0e7d0-0fbb-4ac1-b467-28d41dd49200)
